#!/usr/bin/env bash
set -euo pipefail
_wrix_prek_bin=$(wrix-prek --print-bin-dir)
export PATH="$_wrix_prek_bin:$PATH"
exec prek hook-impl --hook-type=pre-commit --hook-dir "$(dirname "$0")" --script-version 4 -- "$@"
